#!/bin/bash

SQLCMD="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Strong_Password_123 -d master"

until $SQLCMD -Q 'SELECT 1'; do
  echo "Waiting for mssql to be ready.."
  sleep 3
done

echo "Creating database.."
$SQLCMD -i setup.sql